# Generated by Django 2.1 on 2018-11-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sample',
            table='Sample',
        ),
    ]
